### ISSUE TITLE
Dropped events

### ISSUE THREAD

**Issue by eboswort** [PostHog/snowflake-export-plugin#43] opened 2023-05-02 15:35 UTC
This integration is dropping events. I can see events in the Posthog UI which do not show up in snowflake. I reported the bug to Posthog but wanted to post here as well for other folks who are debugging this and trying to figure out what's up.

**Comment by burkaygur** [comment] 2023-05-18 02:05
+1 same issue

**Comment by guillaumelachaud** [comment] 2023-06-01 17:01
I have reached the same conclusion after investigating some missing events in Snowflake. Data shows up in Posthog just fine but some events are missing in Snowflake.

I have done a bit of investigation but I haven't been able to identify a root cause yet:
 - It looks like the export plugin sometimes either fails to run or has no files to run on. When looking at the Snowflake copy history in the information schema, we can see a drop in copy activity that matches the discrepancy in the data (in one case, I have one day with nearly 0 synced events and just a couple of copy queries on that day). You can look into the copy history with:
 ```sql
SELECT
  FILE_NAME,
  STAGE_LOCATION,
  LAST_LOAD_TIME,
  ROW_COUNT,
  ROW_PARSED,
  ERROR_COUNT,
  initcap(replace(STATUS, '_', ' '), ''),
  PIPE_NAME,
  PIPE_CATALOG_NAME,
  PIPE_SCHEMA_NAME,
  FILE_SIZE,
  FIRST_ERROR_MESSAGE,
  FIRST_ERROR_LINE_NUMBER,
  FIRST_ERROR_CHARACTER_POS,
  FIRST_ERROR_COLUMN_NAME,
  ERROR_LIMIT,
  PIPE_RECEIVED_TIME
FROM
  table(
    "YOUR_POSTHOG_DB".INFORMATION_SCHEMA.COPY_HISTORY(
      table_name => '"YOUR_POSTHOG_DB"."PUBLIC"."EVENTS"',
      start_time => TO_TIMESTAMP_LTZ('2023-05-19T07:00:00.000Z', 'AUTO'),
      end_time => TO_TIMESTAMP_LTZ('2023-05-20T07:00:00.000Z', 'AUTO')
    )
  )
ORDER BY
  LAST_LOAD_TIME DESC
 ```

 - The `exportEvents metrics` page in Posthog shows no errors. But the app **logs** show a _lot_ of errors:
 
```
Failed to copy snowflake-export-2023-05-31-20230531-222757.117Z-a69fa7c9b0a1589b.csv,
snowflake-export-2023-05-31-20230531-222758.743Z-81912340ca352a99.csv,
snowflake-export-2023-05-31-20230531-222758.992Z-efab940327d1e991.csv,
snowflake-export-2023-05-31-20230531-222800.063Z-75fe2e2bc5d7c61e.csv,
....
from object storage into Snowflake. Retrying in 24576s.
```
  It is unclear to me:
  - What's causing these copy errors. I haven't found any corresponding logs on Snowflake's end
  - If these errors are properly retried (they are retried up to 15 times according to the plugin code) and if they actually all made it into Snowflake at some point
  - What happens if we reach the limit and these don't get inserted into Snowflake. Will it show up as an error on the metrics page?

I noticed that the `COPY INTO` operation on Snowflake that performs the actual load from the CSV files into the tables, is configured with `ON_ERROR = 'skip_file'`, ([doc](https://docs.snowflake.com/en/sql-reference/sql/copy-into-table#copy-options-copyoptions)), which may or may not be a good thing? I'm not a Snowflake expert so I can't tell if this is a desirable behavior. The sure thing is that error mechanisms are not properly documented in this plugin's readme.

@eboswort Did you hear from Posthog? Did you make any progress in figuring out the problem?

**Comment by eboswort** [comment] 2023-06-01 18:16
@guillaumelachaud Hey, kudos to you for digging in and trying to figure out the root cause. I was really just waiting for Posthog to tell me they'd fixed the issue. 
They acknowledged it and said that they were implementing a new strategy for exporting events which wouldn't have the issue (I guess implying that they were trying to rebuild this rather than fix it). 
They pointed me to this PR: https://github.com/PostHog/posthog/pull/15364 as the first step towards that new solution.

**Comment by hazzadous** [comment] 2023-06-02 06:29
Thanks both. It's running behind schedule but at least the bulk of the work was merged in with https://github.com/PostHog/posthog/pull/15649

We still need to hook up Snowflake as well, and get the frontend merged in.

**Comment by xvello** [comment] 2024-03-07 16:47
Closing as this plugin has been deprecated in favor of our [Snowflake destination for batch exports](https://posthog.com/docs/cdp/batch-exports/snowflake).

**Closed as not planned by xvello** 2024-03-07 16:47 UTC
